apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx1
  name: nginx1
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx1
  type: NodePort

---
nginx:
  uri: "nginx1://nginx1:80"

serviceMonitor:
  additionalLabels:
    release: prometheus
